version: '3.5'
services:
  selenium-hub-test:
    image: selenium/hub:4.9.0
    container_name: selenium-hub-test
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - SE_GRID_MAX_SESSION=10
    networks:
      - selenium4_network

  test_project:
    container_name: new_project
    build: .
    volumes:
      - .:/code
      - .:/host/
      - ./reports:/usr/src/app/reports
    environment:
      - PYTHONUNBUFFERED=1
      - USERDATA=${USER_DATA}
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc-test
      - selenium-hub-test
    env_file:
      - .env
    networks:
      - selenium4_network
    restart: unless-stopped
    command: sh -c "tail -f /dev/null"

  chrome-test:
    image: selenium/node-chrome:4.9.0
    container_name: chrome-test
    shm_size: "2gb"
    volumes:
      - /dev/shm:/dev/shm
      - ./downloads:/home/seluser/Downloads
      - ./entrypoints:/home/seluser/entrypoints
    depends_on:
      - selenium-hub-test
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-test
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - DISPLAY=novnc:0.0
      - SE_HUB_HOST=selenium-hub-test
      - SE_HUB_PORT=4444
    networks:
      - selenium4_network
    ports:
      - "5901"
      - "7901"

  novnc-test:
    image: theasp/novnc
    container_name: novnc-test
    restart: unless-stopped
    environment:
      - DISPLAY_WIDTH=2000
      - DISPLAY_HEIGHT=1000
      - RUN_XTERM=no
    networks:
      - selenium4_network
    ports:
      - 8889:8080

networks:
  selenium4_network:
    driver: bridge
